### ISSUE TITLE
keyword list displayed over folder list, making it unaccessible

### ISSUE THREAD

**Issue by Miyamoto72** [thomascube/roundcube-elastic4mobile#3]
When using elastic skin (by enabling this plugin) and have the folder list of the mailbox displayed the keyword list is laid over the folder names, making them inaccessible. Screenshot will follow.

This may be a problem specific to Kolab, as I'm using Kolab Groupware. It could be an issue with the Elastic skin as well, I just can't tell.

**Comment by Miyamoto72** [comment]
![screenshot_chrome_20180918-192345-01](https://user-images.githubusercontent.com/43384567/45705242-5c5f8180-bb79-11e8-860f-de888da9efb3.jpeg)

**Comment by thomascube** [comment]
What keyword list? This is probably coming from a plugin which is not yet compatible with Elastic. Find out which plugin inserts that keyword list and report to the plugin author. Not related to elastic4mobile.
