### ISSUE TITLE
logout goes to desktop login page

### ISSUE THREAD

**Issue by nuess0r** [thomascube/roundcube-elastic4mobile#5]
Today I updated to roundcube-1.4-rc2 and did also a php composer update.
I use the elastic4mobile plug-in to provide the new elastic skin to mobile phone users. Default skin is not elastic.

During testing I saw a flaw that I overlooked before: After logout on a mobile device the browser first returns to the default login page. When I reload this login page it changes again to the expected elastic login page.

**Comment by AndNovAtor** [comment]
Same with roundcube-1.4.1. I made some dirty workaround.
Btw, @alecpl, what does https://github.com/thomascube/roundcube-elastic4mobile/blob/master/elastic4mobile.php#L14 mean (``public $task = '?(?!logout).*';``)?

**Comment by alecpl** [comment]
It means the plugin is used on all tasks except the logout task.
